// Mocks generated by Mockito 5.0.7 from annotations
// in module_splash/test/app/module/data/repositories/auth_repository_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:commons/shared/auth/local_storage/interfaces/auth_repository_interface.dart'
    as _i3;
import 'package:commons/shared/auth/models/auth_model.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

// ignore_for_file: prefer_const_constructors

// ignore_for_file: avoid_redundant_argument_values

class _FakeAuthModel extends _i1.Fake implements _i2.AuthModel {}

/// A class which mocks [IAuthLocalStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAuthLocalStorage extends _i1.Mock implements _i3.IAuthLocalStorage {
  MockIAuthLocalStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<dynamic> add(_i2.AuthModel? auth) =>
      (super.noSuchMethod(Invocation.method(#add, [auth]),
          returnValue: Future<dynamic>.value(null)) as _i4.Future<dynamic>);
  @override
  _i4.Future<List<_i2.AuthModel>> getAll() =>
      (super.noSuchMethod(Invocation.method(#getAll, []),
              returnValue: Future<List<_i2.AuthModel>>.value(<_i2.AuthModel>[]))
          as _i4.Future<List<_i2.AuthModel>>);
  @override
  _i4.Future<_i2.AuthModel> get(int? id) =>
      (super.noSuchMethod(Invocation.method(#get, [id]),
              returnValue: Future<_i2.AuthModel>.value(_FakeAuthModel()))
          as _i4.Future<_i2.AuthModel>);
  @override
  _i4.Future<dynamic> update(_i2.AuthModel? model) =>
      (super.noSuchMethod(Invocation.method(#update, [model]),
          returnValue: Future<dynamic>.value(null)) as _i4.Future<dynamic>);
  @override
  _i4.Future<dynamic> remove(_i2.AuthModel? user) =>
      (super.noSuchMethod(Invocation.method(#remove, [user]),
          returnValue: Future<dynamic>.value(null)) as _i4.Future<dynamic>);
  @override
  _i4.Future<dynamic> clear() =>
      (super.noSuchMethod(Invocation.method(#clear, []),
          returnValue: Future<dynamic>.value(null)) as _i4.Future<dynamic>);
}
